name: Build and Push Docker Image To AWS ECR
on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - run: docker buildx build -t app .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: public.ecr.aws
          REGISTRY_ALIAS: 897729139176.dkr.ecr.ap-northeast-2.amazonaws.com/first-private-ecr
          REPOSITORY: first-private-ecr
          IMAGE_TAG: latest
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 897729139176.dkr.ecr.ap-northeast-2.amazonaws.com
          docker build -t first-private-ecr .
          docker tag first-private-ecr:latest 897729139176.dkr.ecr.ap-northeast-2.amazonaws.com/first-private-ecr:latest
          docker push 897729139176.dkr.ecr.ap-northeast-2.amazonaws.com/first-private-ecr:latest